Config:
  JoinMessages:
    NormalJoin:
      Title: "&aWelcome %player% to Server"
      SubTitle: "&bThanks for entry in our server"
      Join-Message: "%player% &6entry the server"
      Permission: "join.normal"
      Time: 20
    VipJoin:
      Title: "&cWelcome %player%"
      SubTitle: "&aIf you read this you have permission: vip.join"
      Join-Message: "%player% %Vault_prefix% &7has joined"
      Permission: "join.vip"
      Time: 20
    StaffJoin:
      Title: ""
      SubTitle: ""
      Join-Message: ""
      Permission: "join.staff"
      Time: 20

